<strong>Shortcode Summary</strong>
<p>
For an explanation of these shortcodes, be sure to see <em>WP Integration / Shortcodes &amp; Widget / Product Presentation / Paid Content </em> 
(and also <em>Buy Now</em>). 
</p>
<p>For this browser session only, you may use the <em>AreteX&trade;</em> button in the <strong>WordPress Page Editor</strong> to paste this shortcode into your content. </p>

<p>Paid Content shortcodes generated by this wizard include:<br />
- Not Logged In<br />
- Logged In But Not Authorized<br />
&nbsp;&nbsp;- Buy Now<br />
- Logged In And  Authorized:<br />
</p>
<p>Product, Deliverable and the Manifest can be edited in <em>Catalog &amp; Products / Products / Edit <strong>(pencil icon</strong>)</em> </p>
<p><em><strong>Important Note:</strong></em> Use "text mode" on the page editor when copying and pasting shortcodes to be sure
all embedded HTML is rendered properly.</p>
