<h2>AreteX&trade; Dynamic Content Tag Reference<br />
    <span style="font-size: 60%;"><em>For the Welcome/Account Email</em></span>
</h2>
<p><a target="_blank" href="<?php echo AreteXDocURL().'AreteXDynamicContentReference.pdf' ?>" >Download as PDF</a></p>
<p>AreteX&trade; uses dynamic content tags  to allow you to customize your welcome email. 
When you put a dynamic content tag into your email document, 
AreteX&trade; replaces it with matching "real" information.  Below is a list of most dynamic tags available to you for your welcome email.  
</p>
<p>You can see an example of dynamic content tag usage by selecting the "CSS Diagrams" button, then selecting "Welcome/Account" </p>
<p>Also see the file "new_account.html" in the email_templates sub directory for another example of how dynamic content tags are used. </p>
<table class="aretx-dyamic-tags">
<tr><th>Dynamic Tag</th><th>Substitution Value</th></tr>
<tr ><td colspan="2"><strong>Business Information</strong> - (Most of this information is taken from the information you provide in your AreteX&trade; Account contact screen)</td></tr>
<tr><td>[Biz.business_name]</td><td>Your business name</td></tr>
<tr><td>[Biz.address]</td><td>Your mailing address</td></tr>
<tr><td>[Biz.phone]</td><td>Your primary phone number</td></tr>
<tr><td>[Biz.customer_service_phone]</td><td>Your customer service number. This must match the customer service number you provided to your payment card processor.</td></tr>
<tr><td>[Biz.email]</td><td>Your primary email address</td></tr>
<tr><td>[Biz.public_email]</td><td>Your "public" email address </td></tr>
<tr><td>[Biz.contact]</td><td>Your primary contact name</td></tr>

<tr ><td colspan="2"><br /><strong>Customer Information</strong> - (Most of this information is supplied by the customer on the order form. They can change it later in their CAM.)</td></tr>
<tr><td>[Customer.firstname]</td><td>Customer first name</td></tr>
<tr><td>[Customer.lastname]</td><td>Customer last name</td></tr>
<tr><td>[Customer.email]</td><td>Customer email addreess (uniquely identifies customer to AreteX&trade;)</td></tr>
<tr><td>[Customer.street]</td><td>Billing address street</td></tr>
<tr><td>[Customer.city]</td><td>Billing address city</td></tr>
<tr><td>[Customer.state]</td><td>Billing address state</td></tr>
<tr><td>[Customer.zip]</td><td>Billing address zip code</td></tr>
<tr><td>[Customer.used_coupon_code]</td><td>If they used a tracking code in their order, this is it.</td></tr>
<tr><td>[Customer.business_name]</td><td>Customer's business name</td></tr>

<tr ><td colspan="2"><br /><strong>Order Information</strong> - (Order specific information, most of it generated by AreteX&trade; or supplied by the credit card processor.)</td></tr>
<tr><td>[Order.total]</td><td>Total paid at time of order</td></tr>
<tr><td>[Order.order_number]</td><td>Order number (generated by AreteX&trade;)</td></tr>
<tr><td>[Order.offer_terms]</td><td>Conditions under which the customer's card will be charged.</td></tr>
<tr><td>[Order.masked_pan]</td><td>Masked payment account number. The last four or five digits are visible.</td></tr>
<tr><td>[Order.card_type]</td><td>Type of credit card used (Visa, Master Card, Discover etc.)</td></tr>
<tr><td>[Order.txn_id]</td><td>Credit card transaction number. Uniquely identifies order.</td></tr>

<tr ><td colspan="2"><br /><strong>App Specific Information</strong> - In this case, the App is your WordPress site.</td></tr>
<tr><td>[App.site_url]</td><td>The URL of your wordpress site.</td></tr>
<tr><td>[App.site_title]</td><td>The name of your wordpress site.</td></tr>

</table>