<div class="tabs">
<ul>
<li><a href="#tabs-1">Shortcodes &amp; Widget Overview</a></li>
<li><a href="#tabs-2">Product Presentation</a></li>
<li><a href="#tabs-3">Payee Registration</a></li>
<li><a href="#tabs-4">Coupons &amp; Tracking</a></li>
</ul>
<div id="tabs-1">
<h2>Shortcodes and Widget</h2>
<p>AreteX&trade; makes extensive use of <a href="http://codex.wordpress.org/Shortcode" target="_blank">WordPress shortcodes</a> to connect your eCommerce services to your web site's front end. </p>
<div class="section group"> <!-- ROW -->
    <div class="col span_1_of_4"> <!-- Column -->
        <img src="<?php echo plugins_url('images/editor-button.png',__FILE__); ?>" />
    </div> <!-- END Column -->
    <div class="col span_3_of_4"> <!-- Column -->
    <p>Many (but not all) AreteX&trade; shortcodes can be automatically generated by selecting your desired options with the <em>AreteX&trade; editor button</em> (located on WordPress editor pages). 
    The AreteX&trade; editor button appears on most major WordPress content creation screens, including Pages, Posts and many custom post types.
    </p>
    <p>Details about exactly which shortcodes can be automatically generated can be found under each shortcode category tab. </p>
    <p><strong>Product Presentation </strong> - These are shortcodes that help you display information about your products on your pages, as well as create purchase buttons.</p>
    <p><strong>Payee Registration</strong> - This shortcode allows you to set up a front end registation form for your contributors and referrers.</p>
    <p><strong>Coupons &amp; Tracking</strong> - Has information about the <em>AreteX&trade; Coupon Widget</em> as well as shortcodes to allow you to 
    accept coupons on your site and display information about them.</p>

    </div> <!-- END Column -->

</div> <!-- END ROW -->
 &nbsp;

 

</div>
<div id="tabs-2">
    <div class="tabs">
        <ul>
            <li><a href="#tabs-2a">Product Information</a></li>
            <li><a href="#tabs-2b">Buy Now</a></li>
            <li><a href="#tabs-2c">Paid Content</a></li>
            <li><a href="#tabs-2d">Membership</a></li>            
        </ul>
        <div id="tabs-2a">
        <h2>The [aretex_product_info] Shortcode</h2>
        <p>The shortcode: <em>aretex_product_info</em> allows you to show basic information about the product on your WordPress page.</p>
        <h4>Automatic Generation</h4>
        <p>This shortcode <strong><em>can</em></strong> be automatically generated  with the AreteX&trade; editor button on the WordPress Page/Post editor.<br />
        
        <img id="button-pp-sm" style="cursor: pointer; margin-top: 5px;" src="<?php echo plugins_url('images/editor-button-product-pres-sm.png',__FILE__); ?>" style="display: inline;" /> &nbsp;
        <br /><span style="font-size: 85%;"><em>Click for full size image.</em></span>
        <img id="full-button-pp" style="display: none" src="<?php echo plugins_url('images/editor-button-product-pres.png',__FILE__); ?>"  /> &nbsp;
 
        </p>
        <script>
        jQuery('#button-pp-sm').click(function(e) {
            jQuery('#full-button-pp').lightbox_me({
                centered: true
                });           
        });
        </script>
        
        <h4>Usage Details</h4>         
        
        <p>The shortcode: <em>aretex_product_info</em>  has the format: <br />
        <span style="font-family: 'Courier New', Courier, monospace; font-size: 10pt; font-weight: bold;">[aretex_product_info code='CODE']Information About the Product.[/aretex_product_info]</span><br />
        </p>
        <p>
            The <strong>code</strong> attribute is required.  It is the product code you wish to present information about.
            The <em>aretex_product_info</em> shortcode supports the following <em>substitution fields</em>:<br />
            <span style="font-family: 'Courier New', Courier, monospace; font-size: 10pt; font-weight: bold;">:code:  :name:  :description:  :itemnote:  :regular_price: </span>            
        </p>
        <p>               
            When you use the shortcode generator, it will look something like this.<br />
            <img  src="<?php echo plugins_url('images/sample1.png',__FILE__); ?>" /> &nbsp;
        </p><div class="section group"> <!-- ROW -->
    <div class="col span_4_of_12"> <!-- Column -->

        <p>Each substitution field is replaced by the appropriate product data value when the shortcode is rendered onto your WordPress page. 
        The following illustration shows how the fields in the AreteX&trade; Product  (<em>Catalog &amp; Products / Products </em> (Add or Edit) map to the shortcode substitution values.  
         <span  style="font-size: 85%;"><em>Click on the image  for a full size view.</em></span>
          </p>
            </div> <!-- END Column -->
            <div class="col span_8_of_12"> <!-- Column -->
    
            <img id="button-sub-map" style="cursor: pointer;  margin-top: 5px;" src="<?php echo plugins_url('images/presentation-sc-illus-65.png',__FILE__); ?>"  /> &nbsp;
                   <img id="full-sub-map" style="display: none" src="<?php echo plugins_url('images/presentation-sc-illus.png',__FILE__); ?>"  /> &nbsp;
     
           
            <script>
            jQuery('#button-sub-map').click(function(e) {
                jQuery('#full-sub-map').lightbox_me({
                    centered: true
                    });           
            });
            </script>
            </div> <!-- END Column -->
        </div> <!-- END ROW -->
        <h4>Editing And Displaying</h4>
        <p>You can use the WordPress editor to add your own text and formatting to the <em>aretex_product_info</em> 
        shortcode so you can present the product as you see fit.  
        <br />
        <div class="section group"> <!-- ROW -->
    <div class="col span_1_of_3"> <!-- Column -->
    Formating something like this:<br />
    <img  src="<?php echo plugins_url('images/sample2.png',__FILE__); ?>" />
    </div> <!-- END Column -->
    <div class="col span_2_of_3"> <!-- Column -->
    Would be rendered something like this:<br />
     <img  src="<?php echo plugins_url('images/description.png',__FILE__); ?>" />
    
    </div> <!-- END Column -->
</div> <!-- END ROW -->             
          </p>
            
        
        </div>
        <div id="tabs-2b">
        <h2>The [aretex_buynow] Shortcode</h2>
        <p>The <em>[aretex_buynow]</em> shortcode will generate a "buy now" button for <em>most</em> of the products in your AreteX&trade; database. </p>
        <p style="border-style: solid; border-width: 2px; padding: 4px;"><em>Please Note:</em><strong>Do not use</strong> the <em>[aretex_buynow]</em> shortcode for  
         <strong>Paid Memberships</strong>.  Select the <em>Membership</em> tab for information about <em>Paid Membership</em> purchase buttons.</p>
        <p>The code generated "behind the scenes" with this shortcode will take into account  relevant information, such as the <em>pricing model</em> any  <em>offer code</em> and/or <em>paid referrer</em>, 
        as well as fundamental information (such as the WordPress username and email address) required for basic deliverable authorizations like paid content.   
        </p>
        <p>When the user selects the generated "<em>Buy Now</em>" button, they will be automatically directed to your PCI compliant payment form on the AreteX&trade; server to complete their purchase. </p>
        <h4>Automatic Generation</h4>
        <p>This shortcode <strong><em>can</em></strong> be automatically generated  with the AreteX&trade; editor button on the WordPress Page/Post editor.</p>
        <div class="section group"> <!-- ROW -->

        <div class="col span_5_of_12"> <!-- Column -->
        <p>To automatically generate and paste a "Buy Now" button onto your WordPress page: From your WordPress admin screen, Add or Edit your page or post, then select the <em>AreteX&trade; Editor</em> button.
        On the <em>AreteX&trade; Shortcode Generator</em> popup select the <em>Product Presentation</em> tab, find and select your product, select the <em>Buy Button</em> box, and then <em>Generate &amp; Paste Shortcode</em>.
        <h4>Usage Details</h4>
        <p>The shortcode: <em>aretex_buynow</em>  has the format: <br />
        <span style="font-family: 'Courier New', Courier, monospace; font-size: 10pt; font-weight: bold;">[aretex_buynow code='CODE']<em>button or image html</em>[/aretex_buynow]</span><br />
        </p>
        <p>The <em>code</em> attiribute is mandatory.  It is the product code you are generating the buy button for.</p>
        <p>You may put <em>one</em> <strong><em>button</em></strong> or <strong><em>img</em></strong> tag inside the <em>aretex_buynow</em> shortcode,
        with whatever styling information you need to make it attractive on your site.  As illustrated in the following image:<br />
         <img src="<?php echo plugins_url('images/buy-button-sc.png',__FILE__); ?>" />
          </p>
            
        </div> <!-- END Column --> 
        <div class="col span_7_of_12"> <!-- Column -->

        <img id="button-bnb-sm" style="cursor: pointer; margin-top: 5px;" src="<?php echo plugins_url('images/select-buy-button-65.png',__FILE__); ?>" style="display: inline;" /> &nbsp;
        <br /><span style="font-size: 85%;"><em>Click for full size image.</em></span>
        <img id="button-bnb-full" style="display: none" src="<?php echo plugins_url('images/select-buy-button.png',__FILE__); ?>"  /> &nbsp;
 
        </p>
        <script>
        jQuery('#button-bnb-sm').click(function(e) {
            jQuery('#button-bnb-full').lightbox_me({
                centered: true
                });           
        });
        </script>
        
         <strong>Image of Button Generated by Sample </strong>
        <img id="button-bn-sm" style="cursor: pointer; margin-top: 5px;" src="<?php echo plugins_url('images/button-65.png',__FILE__); ?>" style="display: inline;" /> &nbsp;
        <br /><span style="font-size: 85%;"><em>Click for full size image.</em></span>
        <img id="full-button-bn" style="display: none" src="<?php echo plugins_url('images/button-1.png',__FILE__); ?>"  /> &nbsp;
 
        </p>
        <script>
        jQuery('#button-bn-sm').click(function(e) {
            jQuery('#full-button-bn').lightbox_me({
                centered: true
                });           
        });
        </script>
        
        </div> <!-- END Column -->   
</div> <!-- END ROW -->
          
        </div>
        <div id="tabs-2c">
        <h2>The [aretex_paid_content] Shortcode</h2>
        <p>With the <em>aretex_paid_content</em>  shortcode, you may charge for nearly <em>any</em> type of content you create on your WordPress site.  Only those users who have paid for it will be able to see it.
        Although this is a very flexible shortcode with a lot of options, in its simplest form all you have to do is wrap the shortcode around the content you wish to charge for:
        <br />
        <img src="<?php echo plugins_url('images/simple-pc.png',__FILE__); ?>" />
         </p>
        
        <p>This shortcode is used to <strong>display</strong> different content to your users depending on their <em>authorization status</em> for this deliverable.
        <strong>Note</strong>: <em>Authorization Status</em> in regards to <em>Paid Content</em> refers to a customer's right to access the deliverable.</p>
        
        <p>Although it is not strictly necessary for the customer to have a user account on your WordPress site to <em>purchase</em>  paid content, 
        they must be logged onto your site to <strong>view</strong> paid content.   If the customer purchases paid content <em><strong>without</strong> being logged on</em>, when they <strong><em>do</em> register and login</strong>,  
        the email address they provide on the payment form is matched to their WordPress email address to authenticate proper authorizaton to content.    
        
        </p>  
        <p>
        The exact <em>authorization status</em> of a given deliverable is determined for a specific user
        based on 1) the options you chose when you set up the deliverable, 2) the current payment status, and 3) 
        when the payment was made. 
        </p>
        <h4>Automatic Generation</h4>
        <p>There are <em><strong>two ways</strong></em> to automatically generate  <em>aretex_paid_content</em> shortcodes: 1) the Setup Wizard in AreteX&trade; and 2) the AreteX&trade; Editor button on the WordPress Page/Post editor. </p>
        <h5>The Paid Content Setup Wizard</h5>
        <div class="section group"> <!-- ROW -->

            <div class="col span_6_of_12"> <!-- Column -->
            <img id="pc-wiz-sm" style="cursor: pointer; margin-top: 5px;" src="<?php echo plugins_url('images/pc-wizard-65.png',__FILE__); ?>" style="display: inline;" /> &nbsp;
        <br /><span style="font-size: 85%;"><em>Click for full size image.</em></span>
        <img id="full-pc-wiz" style="display: none" src="<?php echo plugins_url('images/pc-wizard.png',__FILE__); ?>"  /> &nbsp;
 
         
        <script>
        jQuery('#pc-wiz-sm').click(function(e) {
            jQuery('#full-pc-wiz').lightbox_me({
                centered: true
                });           
        });
        </script>
            
            
            </div> <!-- END Column -->
            <div class="col span_6_of_12"> <!-- Column -->            
            <p>The <em>New Paid Content Wizard</em> will automatically create a new <em>Product</em>, a new <em>Paid-Content Deliverable</em>, and generate the most approriate shortcodes for the options you have selected - including the purchase button.</p>
            <p>On the last step of the wizard, you have two choices with the generated shortcodes: 1) Copy and paste them into a text file for later or 2) Paste them into your WordPress page during your current browser session.</p>
            <p><strong><em>Important Note:</em></strong> 1) Session storage is <em>temporary</em>. When you close your browser window, the shortcodes will be lost. 2) Only <em>the latest wizard generated shortcodes</em> are saved in the browser session. </p>
            <p>If you do not plan on using the shortcodes right away, you may want to copy and paste them to a text file on your computer.</p>
            </div> <!-- END Column -->
    
        </div> <!-- END ROW -->
        <div class="section group"> <!-- ROW -->
            <div class="col span_6_of_12"> <!-- Column -->
                <p><strong>To use the shortcodes immediately: </strong><br />
                1) Add or Edit a new WordPress Page, Post or custom post type, where you want the paid content to go.<br />
                2) Select the AreteX&trade; Editor Button on the WordPress editor. <br />
                3) If there are shortcodes stored in session, you will have the option to paste them onto your content immediatley.<br />
                </p>
                <p><em>Note:</em> Once you have pasted the shortcodes onto your Page or Post, be sure to add content your customers are paying for.</p>
                
                
            </div> <!-- END Column -->
            <div class="col span_6_of_12"> <!-- Column -->
            <img id="pc-wiz-sm-2" style="cursor: pointer; margin-top: 5px;" src="<?php echo plugins_url('images/short-code-paste-ins-65.png',__FILE__); ?>" style="display: inline;" /> &nbsp;
        <br /><span style="font-size: 85%;"><em>Click for full size image.</em></span>
        <img id="full-pc-wiz-2" style="display: none" src="<?php echo plugins_url('images/short-code-paste-ins.png',__FILE__); ?>"  /> &nbsp;
 
         
        <script>
        jQuery('#pc-wiz-sm-2').click(function(e) {
            jQuery('#full-pc-wiz-2').lightbox_me({
                centered: true
                });           
        });
        </script>
            </div> <!-- END Column -->

        </div> <!-- END ROW -->
        
        <h5>The AreteX&trade; Editor Button on the WordPress Page/Post Editor</h5>
        <div class="section group"> <!-- ROW -->
    <div class="col span_1_of_3"> <!-- Column -->

        <p>To automatically generate <em>aretex_paid_content</em> shortcodes and paste them into your Pages and Posts, <em><strong>first</strong></em>, navigate to the Page or Post editor on your WordPress admin screen. 
        <em><strong>Next</strong></em>, select the <em>Paid Content</em> tab. Select the paid content <em>deliverable code</em> and the various status conditions you want to address within your conent. <em><strong>Then</strong></em>, generate and paste the shortcodes.
        For a dicussion on valid status condtions and the distinction between  <em>deliverable codes</em> and <em>products</em>, see the next section. </p>
        </div> <!-- END Column -->
        <div class="col span_2_of_3"> <!-- Column -->
    
             <img id="pc-ed-sm-1" style="cursor: pointer; margin-top: 5px;" src="<?php echo plugins_url('images/pc-edit-button-65.png',__FILE__); ?>" style="display: inline;" /> &nbsp;
        <br /><span style="font-size: 85%;"><em>Click for full size image.</em></span>
        <img id="full-ed-pc-1" style="display: none" src="<?php echo plugins_url('images/pc-edit-button-1.png',__FILE__); ?>"  /> &nbsp;
 
         
        <script>
        jQuery('#pc-ed-sm-1').click(function(e) {
            jQuery('#full-ed-pc-1').lightbox_me({
                centered: true
                });           
        });
        </script>
       
        </div> <!-- END Column -->
        </div> <!-- END ROW -->  
        <h5>Usage Details</h5>

        <div id="show_short_code_example">            

<p>The <em>[aretex_paid_content]</em> shortcode is of the following format:<br/>                        
<div style=" font-family: 'Courier New', Courier,  monospace; font-size:10pt; padding: 5px; "
class="ui-widget ui-widget-content  ui-corner-bottom">             
[aretex_paid_content deliverable_code="<strong>CODE</strong>" status="<strong>--SEE BELOW--</strong>"]
---- YOUR CONTENT APPROPRIATE TO STATUS ---
[/aretex_paid_content]
</div>
<p><em><strong>Important Note:</strong></em> Use "text mode" on the page editor when copying and pasting shortcodes to be sure
all embedded HTML is rendered properly.</p>
<p>Both the <em><strong>deliverable_code</strong></em> and <em><strong>status</strong></em> attributes are required. </p>
<p>Paid content is considered by AreteX&trade; to be a <em>deliverable</em>. As explained in <em>Catalog &amp; Products / Delivery Specifications </em> a deliverable can be part of any number of products via the product's <em>manifest</em>. 
        This allows you the flexiblity to bundle your content as you see fit. The <em>deliverable_code</em> lets AreteX&trade; 
        know which content deliverable you are putting on your Page or Post.  
        </p>
<p>Generally speaking, a user is considered <em>Authroized</em>  if they have a timely payment for <em>any product</em> with this <em>deliverable</em> in its <em>manifest</em>. </p>        
<p>The content <em>within</em> the shortcode an be <em>any</em> valid WordPress content, <em>including</em> other shortcodes.
That means you can embed audio, video, file download links, chatroom entrances or any other content you can put in WordPress.  
 </p>        

<p>The <em><strong>status</strong></em> attribute determines the conditions under which the content within the shortcode is displayed.
A full list of valid status condtions are listed below. </p>
        
<h4>Valid <em>status</em> Values</h4>
<table class="gridtable">
<thead>
<tr><th>Status</th><th>Explanation</th><th>Show/Hide</th></tr>
</thead>
<tbody>
<tr><td>Authorized</td><td>User is authorized to view content.  If no status is specified, this status is the default.</td><td><button type="button" class="sc_example_btn">Example</button></td></tr>
<tr class="sc_example"><td colspan="3">
[aretex_paid_content deliverable_code="$deliverable_code" status="Authorized"]
---- YOUR PAID CONTENT GOES HERE ----
[/aretex_paid_content]
</td></tr>

<tr><td>!Authorized</td><td>User is NOT authorized to view content.  The exclamation mark (!) means "NOT".
The reason the user is not authorized is irrelevant.
</td><td><button  type="button" class="sc_example_btn">Example</button></td></tr>
<tr class="sc_example"><td colspan="3">
[aretex_paid_content deliverable_code="$deliverable_code" status="!Authorized"]
---- YOUR 'You are not authorized' CONTENT GOES HERE ----
[/aretex_paid_content]
</td></tr>

<tr><td>Expired</td><td>Only valid when you have a <strong>Duration</strong> specified. The content within the shortcode with this status will be displayed when the duration has passed and has not been renewed. </td><td><button  type="button" class="sc_example_btn">Example</button></td></tr>
<tr class="sc_example"><td colspan="3">
[aretex_paid_content deliverable_code="$deliverable_code" status="Expired"]
---- YOUR 'Your access authorization has expired' CONTENT GOES HERE ----
[/aretex_paid_content]
</td></tr>

<tr><td>!Expired</td><td>The authorization has NOT expired. The exclamation mark (!) means "NOT". </td><td><button  type="button" class="sc_example_btn">Example</button></td></tr>
<tr class="sc_example"><td colspan="3">
[aretex_paid_content deliverable_code="$deliverable_code" status="!Expired"]
---- YOUR 'Your access authorization has not (yet?) expired' CONTENT GOES HERE ----
[/aretex_paid_content]
</td></tr>

<tr><td>Pending</td><td>Only valid when you have an <strong>Availablity</strong> greater than 0. The content within the shortcode with this status will be displayed when the delivery is pending. </td><td><button  type="button" class="sc_example_btn">Example</button></td></tr>
<tr class="sc_example"><td colspan="3">
[aretex_paid_content deliverable_code="$deliverable_code" status="Pending"]
---- YOUR 'Your access authorization is pending' CONTENT GOES HERE ----
[/aretex_paid_content]
</td></tr>

<tr><td>!Pending</td><td>The content within the shortcode with this status will be displayed any time the content is not pending. The exclamation mark (!) means "NOT". </td><td><button  type="button" class="sc_example_btn">Example</button></td></tr>
<tr class="sc_example"><td colspan="3">
[aretex_paid_content deliverable_code="$deliverable_code" status="!Pending"]
---- YOUR 'Your access authorization is not pending' CONTENT GOES HERE ----
[/aretex_paid_content]
</td></tr>


<tr><td>Completed</td><td>Only valid when you have a <strong>Total Re-Auth</strong> specified. The content within the shortcode with this status will be displayed when the maximum number of deliveries has been completed. </td><td><button  type="button" class="sc_example_btn">Example</button></td></tr>
<tr class="sc_example"><td colspan="3">
[aretex_paid_content deliverable_code="$deliverable_code" status="Completed"]
---- YOUR 'Your access authorization has been completed' CONTENT GOES HERE ----
[/aretex_paid_content]
</td></tr>

<tr><td>!Completed</td><td>The content within the shortcode with this status will be displayed when the maximum number of deliveries has NOT been completed. The exclamation mark (!) means "NOT". </td><td><button  type="button" class="sc_example_btn">Example</button></td></tr>
<tr class="sc_example"><td colspan="3">
[aretex_paid_content deliverable_code="$deliverable_code" status="!Completed"]
---- YOUR 'Your access authorization has not  been completed' CONTENT GOES HERE ----
[/aretex_paid_content]
</td></tr>

<tr><td>Authorized|Completed</td><td> <em>(Advanced Useage)</em> The <em>"pipe"</em> symbol (|) means OR. This content will be displayed if the user is Authorized OR the maximum number of deliveries has been completed.<br/>
  <em>Note:</em> ANY of the statuses above may be "OR"ed together. If ANY ONE status in an OR condition is valid, the content will be shown.<br/>
  </td><td><button  type="button" class="sc_example_btn">Example</button></td></tr>
<tr class="sc_example"><td colspan="3">
[aretex_paid_content deliverable_code="$deliverable_code" status="Authorized|Completed"]
---- YOUR APPROPRIATE CONTENT GOES HERE ----
[/aretex_paid_content]
</td></tr>

<tr><td>!Authorized&!Pending</td><td> <em>(Advanced Useage)</em> The <em>"and"</em> symbol (&) means AND. This content will be displayed if the user is NOT Authorized AND NOT Pending.<br/>
  <em>Note:</em> ANY of the statuses above may be "ANDED" together. If ALL statuses in an AND condition are valid, the content will be shown.<br/>
  </td><td><button  type="button" class="sc_example_btn">Example</button></td></tr>
<tr class="sc_example"><td colspan="3">
[aretex_paid_content deliverable_code="$deliverable_code" status="!Authorized&!Pending"]
---- YOUR APPROPRIATE CONTENT GOES HERE ----
[/aretex_paid_content]
</td></tr>

<tr><td>LoggedIn</td><td>The content within the shortcode with this status will be displayed when the user is logged in regardless of the user's authorization status for this deliverable.<br/>
<em>Note:</em> The AND, OR operators (|, &amp;) -- see above -- will NOT work with this status. 
</td><td><button  type="button" class="sc_example_btn">Example</button></td></tr>
<tr class="sc_example"><td colspan="3">
[aretex_paid_content deliverable_code="$deliverable_code" status="LoggedIn"]
---- YOUR USER IS LOGGED IN CONTENT GOES HERE ----
[/aretex_paid_content]
</td></tr>

<tr><td>!LoggedIn</td><td>The content within the shortcode with this status will be displayed when the user is NOT logged in. The exclamation mark (!) means "NOT". <br/>
<em>Note:</em> The AND, OR operators (|, &amp;) -- see above -- will NOT work with this status.  
</td><td><button  type="button" class="sc_example_btn">Example</button></td></tr>
<tr class="sc_example"><td colspan="3">
[aretex_paid_content deliverable_code="$deliverable_code" status="!LoggedIn"]
---- YOUR USER IS NOT LOGGED IN CONTENT GOES HERE ----
[/aretex_paid_content]
</td></tr>

</tbody>
</table>
</div>
<script>
jQuery('.sc_example_btn').click(function(){
    var row = jQuery(this).closest('tr');
    var next = row.next();
    next.toggle();
});
jQuery('.sc_example').hide();
</script>            
            
        
        
              
        </div>
        
        <div id="tabs-2d">
        <h2>Paid Membership Purchase Shortcodes </h2>
        <p>There are three shortcodes related membership purchase.  They are to be used instead of [<em>aretex_buynow</em>]: <br />
        <em>[aretex_paid_registration]</em> - This generates a simple front-end registration form for customers to sign up with.<br />
        <em>[aretex_register_button]</em> - This shortcode goes <em>inside</em> the aretex_paid_registration content and generates a "buy" button.<br />
        <em>[aretex_role_button]</em> - This shortcode generates a "buy" button for a membership upgrade.
        </p>
        <p>You should use these shortcodes to sell any <em><strong>Product</strong></em> with a <strong><em>Membership</em> deliverable</strong> in its <em><strong>Manifest</strong></em>. 
        That is because behind the scenes, these shortcodes work with the WordPress registration system as well as the WordPress Roles and Capablities system.        
        </p>
        <p>Paid Membership purchase shortcodes have two purposes: 1) <em>Registration</em> and 2) <em>"Upgrade" Payment</em>.  
        <em>Registration</em> allows non-members to sign up and pay for access to your site.  The role they are assigned when payment is complete depends on the product and the membership deliverable in the associated manifest.
        <em>Upgrade Payments</em> allow existing members to purchase a new role. 
        <em>Note:</em> It's a really good idea to only have <em>one</em> membership deliverable in any given manifest.  
        </p>
        <p>You <em><strong>may</strong></em> have other types of deliverables (i.e. <em>paid content</em>) in the product manifest when using <em>Paid Membership</em> purchase shortcodes. 
        AreteX&trade; will handle delivery authorization of other deliverables appropriately when it is bundled with a membership purchase. 
        (The converse is <em>not</em> true. Please do not use the <em>aretex_buy_now</em> shortcode for selling memberships.) </p>
        <h4>Automatic Generation</h4>
        <p>There are <em><strong>two ways</strong></em> to automatically generate paid membership shortcodes: 1) the Setup Wizard in AreteX&trade; and 2) the AreteX&trade; Editor button on the WordPress Page/Post editor. </p>
        <h5>The Paid Membership Setup Wizard</h5>
        <div class="section group"> <!-- ROW -->
            <div class="col span_6_of_12"> <!-- Column -->
              <img id="button-pm-sm" style="cursor: pointer; margin-top: 5px;" src="<?php echo plugins_url('images/pm-wiz-65.png',__FILE__); ?>" style="display: inline;" /> &nbsp;
                <br /><span style="font-size: 85%;"><em>Click for full size image.</em></span>
                <img id="full-button-pm" style="display: none" src="<?php echo plugins_url('images/pm-wiz-1.png',__FILE__); ?>"  /> &nbsp;
         
                </p>
                <script>
                jQuery('#button-pm-sm').click(function(e) {
                    jQuery('#full-button-pm').lightbox_me({
                        centered: true
                        });           
                });
                </script>
            </div> <!-- END Column -->
            <div class="col span_6_of_12"> <!-- Column -->
            
            <p>The <em>New Paid Membership Wizard</em> will automatically create a new <em>Product</em>, a new <em>Paid Membership Deliverable</em>, and generate the most approriate shortcodes for the options you have selected - including the purchase button.</p>
            <p>On the last step of the wizard, you have two choices with the generated shortcodes: 1) Copy and paste them into a text file for later or 2) Paste them into your WordPress page during this browser session.</p>
            <p><strong><em>Important Note:</em></strong> 1) Session storage is <em>temporary</em>. When you close your browser window, the shortcodes will be lost. 2) Only <em>the latest wizard generated shortcodes</em> are saved in the browser session. </p>
            <p>If you do not plan on using the shortcodes right away, you may want to copy and paste them to a text file on your computer.</p>

            
            
            </div> <!-- END Column -->
        </div> <!-- END ROW -->
        
                <div class="section group"> <!-- ROW -->
            <div class="col span_6_of_12"> <!-- Column -->
                <p><strong>To use the shortcodes immediately: </strong><br />
                1) Add or Edit a new WordPress Page, Post or custom post type, where you want the membership purchase buttons to go.<br />
                2) Select the AreteX&trade; Editor Button on the WordPress editor. <br />
                3) If there are shortcodes stored in session, you will have the option to paste them onto your content immediately.<br />
                </p>
                <p><em>Note:</em> Once you have pasted the shortcodes onto your Page or Post, be sure to update the button text.</p>
                
                
            </div> <!-- END Column -->
            <div class="col span_6_of_12"> <!-- Column -->
            <img id="pm-wiz-sm-2" style="cursor: pointer; margin-top: 5px;" src="<?php echo plugins_url('images/sc-paste-ins-pm-65.png',__FILE__); ?>" style="display: inline;" /> &nbsp;
        <br /><span style="font-size: 85%;"><em>Click for full size image.</em></span>
        <img id="full-pm-wiz-2" style="display: none" src="<?php echo plugins_url('images/sc-paste-ins-pm.png',__FILE__); ?>"  /> &nbsp;
 
         
        <script>
        jQuery('#pm-wiz-sm-2').click(function(e) {
            jQuery('#full-pm-wiz-2').lightbox_me({
                centered: true
                });           
        });
        </script>
            </div> <!-- END Column -->

        </div> <!-- END ROW -->
                <h5>The AreteX&trade; Editor Button on the WordPress Page/Post editor</h5>
        <div class="section group"> <!-- ROW -->
    <div class="col span_1_of_3"> <!-- Column -->

        <p>To automatically generate Paid Membership purhcase shortcodes and paste them into your Pages and Posts, <em>first</em>, navigate to the Page or Post editor on your WordPress admin screen. 
        <em>Next</em>, select the <em>Paid Membership</em> tab.  Follow the prompts for the membership product you wish to sell. </p>        
        </div> <!-- END Column -->
        <div class="col span_2_of_3"> <!-- Column -->
    
             <img id="pm-ed-sm-1" style="cursor: pointer; margin-top: 5px;" src="<?php echo plugins_url('images/pm-ed-btn-65.png',__FILE__); ?>" style="display: inline;" /> &nbsp;
        <br /><span style="font-size: 85%;"><em>Click for full size image.</em></span>
        <img id="full-ed-pm-1" style="display: none" src="<?php echo plugins_url('images/pm-ed-btn.png',__FILE__); ?>"  /> &nbsp;
 
         
        <script>
        jQuery('#pm-ed-sm-1').click(function(e) {
            jQuery('#full-ed-pm-1').lightbox_me({
                centered: true
                });           
        });
        </script>
        </div> <!-- END Column -->
        </div> <!-- END ROW -->  
        <h5>Usage Details</h5>
        <p><strong>Registration: </strong> - What follows is an illustration of how <em>[aretex_paid_registration]</em> and <em>[aretex_register_button]</em> work together.

<img id="reg-fm-sm" style="cursor: pointer; margin-top: 5px;" src="<?php echo plugins_url('images/reg-sc-format-65.png',__FILE__); ?>" style="display: inline;" /> &nbsp;
        <br /><span style="font-size: 85%;"><em>Click for full size image.</em></span>
        <img id="reg-fm-full" style="display: none" src="<?php echo plugins_url('images/reg-sc-format.png',__FILE__); ?>"  /> &nbsp;
 
         
        <script>
        jQuery('#reg-fm-sm').click(function(e) {
            jQuery('#reg-fm-full').lightbox_me({
                centered: true
                });           
        });
        </script>        
                        
        </p>
        <div class="section group"> <!-- ROW -->
    <div class="col span_6_of_12"> <!-- Column -->

        <p>The <em>[aretex_paid_registration]</em>  shortcode generates the registration form. It needs to contain <em>at least</em> one <em>[aretex_register_button]</em> shortcode to function. </p>
        <p>If <em>[aretex_register_button]</em>  <strong>does not</strong> have a <em>product_code</em> attribute, it will be a free 
        registration. Free registrations are processed through the normal WordPress registration system, and not AreteX&trade;.</p>
        <p>If <em>[aretex_register_button]</em> <strong>does</strong> have a <em>product_code</em> attribute, the customer who selects the generated button will be sent to your PCI compliant payment form on the AreteX&trade; server. 
        AreteX&trade; will authorize the appropriate access upon completed payment.  The temporary password will emailed to the customer by your WordPress system (not the AreteX&trade; Server). The temporary password will be the Transaction Id generated by the credit card processor.
        This process makes use of your WordPress WP-Cron to poll AreteX&trade; for pending registration authorizations. 
        </p>
        <p>You may put any content you wish into the <em>[aretex_paid_registration]</em> shortcode (including other shortcodes).  
        It will appear <em>after</em> the registration form. </p>
        <p>If <em>[aretex_register_button]</em> should contain only <strong>button</strong> or <strong>img</strong> tags, you may style as you wish. 
        Note that this plugin uses ajax for registration setup, so any <em>button tag</em> should contain the <strong><em>type="button"</em></strong> attribute.</p>
       </div> <!-- END Column -->
       <div class="col span_6_of_12"> <!-- Column -->
       <strong>Sample of Form Generated by Illustrated Shortcode</strong><br />
       <img id="reg-fm-sm-1" style="cursor: pointer; margin-top: 5px;" src="<?php echo plugins_url('images/reg-form-65.png',__FILE__); ?>" style="display: inline;" /> &nbsp;
        <br /><span style="font-size: 85%;"><em>Click for full size image.</em></span>
        <img id="reg-fm-samp" style="display: none" src="<?php echo plugins_url('images/reg-form.png',__FILE__); ?>"  /> &nbsp;
 
         
        <script>
        jQuery('#reg-fm-sm-1').click(function(e) {
            jQuery('#reg-fm-samp').lightbox_me({
                centered: true
                });           
        });
        </script> 
       </div> <!-- END Column -->
    </div> <!-- END ROW -->     
         
        <p><strong>Role Upgrade</strong> - Use the <em>[aretex_role_button]</em> shortcode to generate a "buy" button for a membership upgrade.
        </p>
        <p>The shortcode: <em>aretex_role_button</em>  has the format: <br />
        <span style="font-family: 'Courier New', Courier, monospace; font-size: 10pt; font-weight: bold;">[aretex_role_button product_code='CODE']<em>button or image html</em>[/aretex_buynow]</span><br />
        </p>
        <p>The <em>product_code</em> attiribute is mandatory.  It is the product code you are generating the buy button for.</p>
        <p>You may put <em>one</em> <strong><em>button</em></strong> or <strong><em>img</em></strong> tag inside the <em>aretex_role_button</em> shortcode,
        with whatever styling information you need to make it attractive on your site.  It is illustrated in the following image:<br />
         <img src="<?php echo plugins_url('images/role-button-sc.png',__FILE__); ?>" />
          </p>

        <p><em>Note:</em> It is a "best practice" to use your chosen membership management plugin to only display an 
        upgrade option to members who 1) are not in the role  or 2) have not upgraded past the role.  (i.e don't show a "Silver Upgrade" to a "Gold" user.)  </p>
        
        </div>
    </div>
</div>
<div id="tabs-3">
<h2>Payee Registration</h2>
<p>Whether a payee is a <em>Referrer</em>, a <em>Contributor</em> or both they will need to be registered on your site to access their <em>Payment Tracking and Reporting</em>  screen (PTR).</p>
<p>There are two ways to register payees: <em>Back End</em> and <em>Front End</em>. Regardless of which way they are assigned, 
they will be required to agree to both <em>your</em> terms of service and the AreteX&trade; terms of service before having full access to their PTR screen. (See <em>WP Integration/ PTR Integration</em> for more details.) </p>
<p>  
For <em>Back End</em> registration, see <em>Reports &amp; Management / Payees / Payee Management / Add</em>.
If your payee is already a member of your site, select their username in the Payee Managment screen when you Add or Edit their record.
</p>
<p>The rest of this tab addresses <em>Front End</em> payee registration. 
<em>Front End</em> payee registration allows people who are currently not members of your web site to sign up from a page on your site. </p>
<h4>The [aretex_payee_signup] Shortcode</h4>
<div class="section group"> <!-- ROW -->
    <div class="col span_7_of_12"> <!-- Column -->

<p>The <em>aretex_payee_signup</em> <strong>cannot</strong> be automatically generated by any wizard or from the AreteX&trade; editor button on the WordPress Page/Post editor.
When you put the shortcode <strong>[aretex_payee_signup]</strong> onto a WordPress Page or Post, it will generate a special registration form. 
When a potential payee signs up using this form, they are registered as a user on your  site with the role <em>AreteX Payee</em>.  
WordPress will send them their temporary password as is usual.  
When they sign on to their user dashboard, the <em>Payment Tracking and Reporting</em> (PTR) menu option will be available to them. See <em>WP Integration/ PTR Integration</em> for information on the PTR screen.</p>
<p>If you put the <em>[aretex_payee_signup]</em> shortcode on your page without any modifications, it will generate the default sign up form.</p>
<p>You may modify the payee sign up form by adding attributes and content. </p>

<h5>Attributes</h5> 
<p>The <strong>[aretex_payee_signup]</strong> shortcode supports the following attributes: <em>captcha</em>,  <em>commission_group</em> and <em>parent</em>. </p>
<strong><em>captcha</em></strong>
<p>The <strong><em>captcha</em></strong> attribute has three options: <em>None</em>, <em>visualCaptcha</em> (Default) and <em>visualCaptcha1</em> - These attribute values <em>are</em> case-sensative.
<ul style="text-indent: -1.0em; margin-left: 1.5em; font-size: 12px;">
<li><strong>None</strong> - No captcha is displayed.</li>
<li><strong>visualCaptcha</strong> (default) - This plugin uses a modified copy of <a href="http://visualcaptcha.net" target="_blank">Visual Captcha</a> version: 4.2.0 to provide additonal security to discourage automated sign ups for payment.
The user will be asked to drag and drop a specific image into the circle.
See the image of the <em>Default Payee Registration Form</em> for an example.  </li>
 <li><strong>visualCaptcha1</strong> This is an alternate arrangement of the visualCaptcha graphics. 
   
 </li>

</ul>
</p> 
<strong><em>commission_group</em></strong>
<p>The <em><strong>commission_group</strong></em> attribute is specifically for <em>referrer</em> registration. If the value of the <strong><em>commission_group</em></strong> 
attribute is a valid <strong>commission group code</strong> (See <em>Setup / Payouts / Commission Structures</em>) the new payee will automatically be assigned to that commission group upon successful registration.
<br /><em><strong>Example:</strong></em> <span style="font-family: 'Courier New', Courier, monospace; font-size: 10pt; font-weight: bold;">[aretex_payee_signup commission_group='AFF1']</span><br />
(This would assign the new registrant to the commission group with the code <em>AFF1</em>, if such a commission group exists in your AreteX&trade; database.)
 The default value of <em><strong>commission_group</strong></em> is <strong>None</strong>.
</p>
<strong><em>parent</em></strong>
<p>The <em><strong>parent</strong></em> attribute is specifically for <em>referrer</em> registration when you have a <em>commission_group</em>
with a <em>multi-tier commission structure</em>. The default value for this attribute is <strong>None</strong>.
</p>
<p>The attribute determines which payee will get the 2nd tier commission when this new referrer makes a sale. (That payee is known as the "Upline" payee, or "parent")</p>
<p>If the attribute value is <strong>tracking</strong>, then the upline payee is determined by the referral tracking code.  The person who referred the new registrant (either by URL or Coupon) 
will receive the 2nd Tier commission.
<br /><em><strong>Example:</strong></em> <span style="font-family: 'Courier New', Courier, monospace; font-size: 10pt; font-weight: bold;">[aretex_payee_signup parent="tracking" commission_group='AFF1']</span><br />
</p>
<p>If the attribute value is a valid <strong>WordPress User Name</strong> that user will be the upline payee. Of course, this requires that the specified WordPress user <em>also</em> be registered as a payee. 
<p>The specified payee will always receive the 2nd Tier commission. The following example assumes you have a WordPress user with the username <em>AffiliateManager</em>. 
<br /><em><strong>Example:</strong></em> <span style="font-family: 'Courier New', Courier, monospace; font-size: 10pt; font-weight: bold;">[aretex_payee_signup parent="AffiliateManager" commission_group='AFF1']</span><br />
</p>
<h5>Content</h5>
<p>You may customize the registration button by putting a single <em><strong>button</strong></em> or <strong><em>img</em></strong> tag within the shortcode content section.
You may style the button as you need to match your site.
</p>
<p>To add a customized button or button image use this format: <span style="font-family: 'Courier New', Courier, monospace; font-size: 10pt; font-weight: bold;">[aretex_payee_signup]<em>Your Image or Button HTML</em>[/aretex_payee_signup]</span></p>
<p>See the image <em>Adding a Custom Button</em> for an example.</p>
    </div> <!-- END Column -->
    <div class="col span_5_of_12"> <!-- Column -->
    <strong>Default Payee Registration Form</strong><br />
    <img id="button-rf-sm" style="cursor: pointer; margin-top: 5px;" src="<?php echo plugins_url('images/payee-reg-65.png',__FILE__); ?>" style="display: inline;" /> &nbsp;
        <br /><span style="font-size: 85%;"><em>Click for full size image.</em></span>
        <img id="full-button-rf" style="display: none" src="<?php echo plugins_url('images/payee-reg.png',__FILE__); ?>"  /> &nbsp;
 
        </p>
        <script>
        jQuery('#button-rf-sm').click(function(e) {
            jQuery('#full-button-rf').lightbox_me({
                centered: true
                });           
        });
        </script>

        <p><strong>When Captcha attibute is <em>visualCaptcha1</em></strong><br />
        <img src="<?php echo plugins_url('images/vc1.png',__FILE__); ?>" /> 
        </p>
        <p><strong>Adding a Custom Button </strong><br />
        <img src="<?php echo plugins_url('images/payee-reg-content.png',__FILE__); ?>" /> 
        </p>

    </div> <!-- END Column -->
</div> <!-- END ROW -->

</div>
<div id="tabs-4">
<h2>Coupons &amp; Tracking</h2>
<p>For more information on setting up Coupons and Tracking codes see <em>Catalog &amp; Products / Coupons &amp; Tracking</em> </p>
<p><em>Note:</em> None of the coupon shortcodes are automatically generated by any wizard or editor button.</p>
<h4>Receiving Tracking Codes</h4>
<p>AreteX&trade; can receive a tracking code either in the URL or as a "<em>Coupon Code</em>". 
This section addresses receiving it as a <em>Coupon Code</em>. 
For more information about receiving it on the URL see <em>WP Integration / PTR Integration</em>   </p>
<h5>AreteX&trade; Coupon Widget</h5>
<div class="section group"> <!-- ROW -->
    <div class="col span_6_of_12"> <!-- Column -->
    <p>
This plugin provides a <a href="http://codex.wordpress.org/WordPress_Widgets" target="_blank">WordPress Widget</a> 
that you can place on your site to recieve a coupon code.  Like all WordPress Widgets, you may install it by going to 
<em>Appearance / Widgets</em> on your WordPress admin screen, then dragging it to your desired location.
</p>
<p>Most of the options are self-explanitory.  The "<em>Current Coupon Text</em>"  option may require some addtional explanation. After a customer enters a <strong>valid</strong> coupon code, the "<em>Current Coupon Text</em>" is displayed at the bottom of the widget.  </p>
<p>The primary purpose of the "<em>Current Coupon Text</em>" is to provide the user with assurance that "something happened" when they entered a valid <em>Coupon Code</em>.
It will be displayed whenever a valid tracking code is in use (even if the tracking code came in via the URL).
</p>
<p>You are provided with the following substitution values. You may use any, all or none of them as you see fit:
<ul style="text-indent: -1.0em; margin-left: 1.5em; font-size: 12px;">
<li><strong>:tracking:</strong> - This echos back the actual code in use.</li>
<li><strong>:description:</strong> - This is the offer description (See <em>Catalog &amp; Products / Coupons &amp; Tracking</em> / Offer Codes).</li>
<li><strong>:referrer:</strong> - This is the name of the person who provided the tracking code.</li>
</ul>

</p>
    </div> <!-- END Column -->
    <div class="col span_6_of_12"> <!-- Column -->
    <strong>Image of the AreteX&trade; Coupon Widget</strong><br />
     <img src="<?php echo plugins_url('images/coupon-widget.png',__FILE__); ?>" />
    </div> <!-- END Column -->
</div> <!-- END ROW -->
<h5>The [aretex_coupon_info] Shortcode</h5>
<p>The <em><strong>[aretex_coupon_info]</strong></em> shortcode <em>cannot</em> be automatically generated with any wizard or on the AreteX&trade; editor button.</p>
<p>This shortcode allows you to put information about the current coupon in use on any Page or Post you which.  
It has essentially the same functionality as The "<em>Current Coupon Text</em>"  option in the coupon widget.  
</p>
<div class="section group"> <!-- ROW -->
    <div class="col span_6_of_12"> <!-- Column -->


<p>The shortcode is of the form:
<span style="font-family: 'Courier New', Courier, monospace; font-size: 10pt; font-weight: bold;">[aretex_coupon_info] --- YOUR CONTENT ---[/aretex_coupon_info]</span><br />
You are provided with the following substitution values. You may use any, all or none of them as you see fit:
<ul style="text-indent: -1.0em; margin-left: 1.5em; font-size: 12px;">
<li><strong>:tracking:</strong> - This echos back the actual code in use.</li>
<li><strong>:description:</strong> - This is the offer description (See <em>Catalog &amp; Products / Coupons &amp; Tracking</em> / Offer Codes).</li>
<li><strong>:referrer:</strong> - This is the name of the person who provided the tracking code.</li>
</ul>
</p>
<p>You can see what any of these are for any given tracking code (or Splash Code) with the Tracking Code Validator (<em>Catalog &amp; Products / Coupons &amp; Tracking / Full Tracking)  </em></p>
<p>If there is <strong><em>no valid</em></strong> coupon code in use, by default the shortcode will <strong>not</strong> generate <em>any</em> text.</p>
<p>The <em>[aretex_coupon_info]</em> shortcode supports the following <em><strong>optional</strong> attributes</em>.  
<ul style="text-indent: -1.0em; margin-left: 1.5em; font-size: 12px;">
<li><strong>allow_invalid</strong> - This is <em>false</em> by default, you can override it by setting it to "true" (i.e.) 
<em>[aretex_coupon_info <strong>allow_invalid="true"</strong>]</em> - With this setting the shortcode will generate text, even if no valid coupon is in use.</li>
<li><strong>tracking</strong> - This is the tracking value you want to display if no valid tracking code is in use: (i.e.) <em>[aretex_coupon_info <strong>tracking="You have no valid coupon"</strong>]</em>.</li>
<li><strong>description</strong> - This is displayed if there is no valid offer description - (i.e.) <em>[aretex_coupon_info <strong>description="Thank you for visiting."</strong>]</em>  </li>
<li><strong>referrer</strong> - This is displayed if there is no referrer, whether it's because the coupon is invalid 
or there was no referrer in the tracking code - <em>[aretex_coupon_info <strong>referrer="Our Store"</strong>]</em> </li>
</ul>
</p>     
</div> <!-- END Column -->
    <div class="col span_6_of_12"> <!-- Column -->

<br /><strong>Image of the Tracking Code Validator</strong><br />

<img id="button-cv-sm" style="cursor: pointer; margin-top: 5px;" src="<?php echo plugins_url('images/tracking-code-map-65.png',__FILE__); ?>" style="display: inline;" /> &nbsp;
        <br /><span style="font-size: 85%;"><em>Click for full size image.</em></span>
        <img id="full-button-cv" style="display: none" src="<?php echo plugins_url('images/tracking-code-map.png',__FILE__); ?>"  /> &nbsp;
       
        <script>
        jQuery('#button-cv-sm').click(function(e) {
            jQuery('#full-button-cv').lightbox_me({
                centered: true
                });           
        });
        </script>
<p><strong>Widget and Shortcode Example</strong></p>
<img id="button-cx-sm" style="cursor: pointer; margin-top: 5px;" src="<?php echo plugins_url('images/coupon-sample-60.png',__FILE__); ?>" style="display: inline;" /> &nbsp;
        <br /><span style="font-size: 85%;"><em>Click for full size image.</em></span>
        <img id="full-button-cx" style="display: none" src="<?php echo plugins_url('images/coupon-sample.png',__FILE__); ?>"  /> &nbsp;
       
        <script>
        jQuery('#button-cx-sm').click(function(e) {
            jQuery('#full-button-cx').lightbox_me({
                centered: true
                });           
        });
        </script>

    </div> <!-- END Column -->
</div> <!-- END ROW -->

<h5>The [aretex_coupon_box] Shortcode</h5>
<p>In addition to the <em>AreteX&trade; Coupon Widget</em>, you may accept coupons on any page of your site using the
[<em>aretex_coupon_box</em>] shortcode.  The widget is <strong>not</strong> required when using the [<em>aretex_coupon_box</em>] shortcode.
</p>
<p>The shortcode is of the form <strong>[aretex_coupon_box submit="Submit Coupon Code"]Your content[/aretex_coupon_box]</strong> </p>
<div class="section group"> <!-- ROW -->
    <div class="col span_6_of_12"> <!-- Column -->

<p>Any content you provide will be displayed <em>above</em> the coupon input box. 
The <em><strong>submit</strong></em> attribute is optional. It is the text that will appear <em>inside</em> the submit button.
If you do not provide text, the button will say <em>"Submit Coupon Code"</em></p>
<p>In order to help you style the coupon box for your site or theme, the following css classes are used.
<ul style="text-indent: -1.0em; margin-left: 1.5em; font-size: 12px;">
<li><strong>aretex_coupon_form_wrapper</strong> - The entire form is wrapped in a <strong>div</strong> with this class.  </li>
<li><strong>aretex_coupon_submit</strong> - This is the css class of the submit button. </li>
</ul>
</p>
<p>
By default, these classes have no definition, but if you wish to stylize the coupon box, you should define them in your stylesheet.
</p>
    </div> <!-- END Column -->
    <div class="col span_6_of_12"> <!-- Column -->
    <strong>[aretex_coupon_box] Example</strong><br />
     <img src="<?php echo plugins_url('images/secret-offer.png',__FILE__); ?>" />
    </div> <!-- END Column -->    
</div> <!-- END ROW -->
</div>

</div>



<script>
jQuery('.tabs').tabs();
</script>